[tool.poetry]
name = "relative-value-credit"
version = "0.1.0"
description = "A framework for Relative Value Credit analysis and backtesting."
authors = ["dbenarous@groupam-am.fr"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.3.0"
numpy = "^1.21.0"
scikit-learn = "^0.24.0"
matplotlib = "^3.4.0"
statsmodels = "^0.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"